# Generated by Django 4.2.23 on 2025-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asset',
            name='account',
            field=models.CharField(default='', help_text='Custody account (empty string instead of UNKNOWN)', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='bank',
            field=models.CharField(default='', help_text='Custody bank (empty string instead of UNKNOWN)', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='client',
            field=models.CharField(db_index=True, default='DEFAULT', help_text='Client code for asset isolation', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='account',
            field=models.CharField(default='', help_text='Account identifier (empty string instead of UNKNOWN)', max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='bank',
            field=models.CharField(default='', help_text='Bank name (empty string instead of UNKNOWN)', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(default='', help_text='Account identifier (empty string instead of UNKNOWN)', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.CharField(default='', help_text='Bank name (empty string instead of UNKNOWN)', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='', help_text='Transaction identifier (empty string instead of UNKNOWN)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('ticker', 'bank', 'account', 'client')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['client', 'ticker'], name='portfolio_a_client_32f8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['client', 'bank', 'account'], name='portfolio_a_client_b74e2f_idx'),
        ),
    ]
