# Generated by Django 4.2.23 on 2025-07-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fix_custody_based_assets'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('ticker', 'cusip', 'name', 'bank', 'account', 'client')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['cusip', 'bank', 'account'], name='portfolio_a_cusip_fa94cf_idx'),
        ),
    ]
