# Generated by Django 4.2.23 on 2025-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_fix_asset_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Annual dividend yield percentage for equities', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='estimated_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated estimated annual income from position', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Face value for bonds (defaults to market_value if not specified)', max_digits=15, null=True),
        ),
    ]
