# Generated by Django 4.2.23 on 2025-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_asset_dividend_yield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='has_rolled_accounts',
            field=models.BooleanField(default=False, help_text='True if this snapshot contains rolled-over account data'),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='rollover_summary',
            field=models.JSONField(blank=True, help_text="Summary: {'CS_SP': '2025-07-24', 'LO_SP': '2025-07-24'}", null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='is_rolled_over',
            field=models.BooleanField(default=False, help_text='True if this position was rolled over from previous date'),
        ),
        migrations.AddField(
            model_name='position',
            name='rolled_from_date',
            field=models.DateField(blank=True, help_text='Original date this position was copied from', null=True),
        ),
    ]
