# Generated by Django 4.2.23 on 2025-08-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_add_rollover_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(default='database_update', max_length=50)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('PROCESSING', 'Processing'), ('ERROR', 'Error')], default='IDLE', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_message', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portfolio_processing_status',
                'unique_together': {('process_type',)},
            },
        ),
    ]
