# Generated by Django 4.2.23 on 2025-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_add_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField(db_index=True, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('client_count', models.IntegerField(default=0)),
                ('total_positions', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'portfolio_date_processing_log',
                'ordering': ['-process_date'],
            },
        ),
        migrations.CreateModel(
            name='AggregatedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_key', models.CharField(db_index=True, help_text='Unique identifier: ALL_CLIENTS, CLIENT_ABC, etc.', max_length=50, unique=True)),
                ('total_aum', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_inception_dollar', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('weighted_inception_percent', models.FloatField(default=0)),
                ('total_annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('client_count', models.IntegerField(default=0)),
                ('asset_allocation', models.JSONField(default=dict, help_text='Pre-aggregated asset allocations')),
                ('chart_data', models.JSONField(default=dict, help_text='Pre-calculated chart data')),
                ('last_date_processed', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portfolio_aggregated_metrics',
                'indexes': [models.Index(fields=['aggregation_key'], name='portfolio_a_aggrega_f9347d_idx'), models.Index(fields=['last_updated'], name='portfolio_a_last_up_2feadb_idx')],
            },
        ),
    ]
