# Generated by Django 4.2.23 on 2025-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_add_dashboard_cache_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAggregatedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('client_filter', models.CharField(db_index=True, default='ALL', max_length=10)),
                ('total_aum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_inception_dollar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weighted_inception_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_annual_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('client_count', models.IntegerField()),
                ('asset_allocation_data', models.JSONField(help_text='Aggregated asset allocation for this date')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portfolio_date_aggregated_metrics',
            },
        ),
        migrations.DeleteModel(
            name='AggregatedMetrics',
        ),
        migrations.DeleteModel(
            name='DateProcessingLog',
        ),
        migrations.AddIndex(
            model_name='dateaggregatedmetrics',
            index=models.Index(fields=['-snapshot_date', 'client_filter'], name='portfolio_d_snapsho_2c6564_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dateaggregatedmetrics',
            unique_together={('snapshot_date', 'client_filter')},
        ),
    ]
