# Generated by Django 4.2.23 on 2025-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_add_bond_maturity_dashboard_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cusip',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('QUARTERLY', 'Quarterly Report'), ('ANNUAL', 'Annual Report'), ('BOND_ISSUER', 'Bond Issuer Report'), ('BOND_MATURITY', 'Bond Maturity Report'), ('EQUITY_BREAKDOWN', 'Equity Breakdown Report'), ('CASH_POSITION', 'Cash Position Report'), ('MONTHLY_RETURNS', 'Monthly Returns by Custody'), ('TOTAL_POSITIONS', 'Total Positions Report')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(default='', help_text='Account identifier (empty string instead of UNKNOWN)', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='', help_text='Transaction identifier (empty string instead of UNKNOWN)', max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=150),
        ),
    ]
