# Generated by Django 4.2.23 on 2025-10-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_asset_cusip_alter_report_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateaggregatedmetrics',
            name='total_period_return_dollar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aggregated this-period dollar returns (sum across all clients)', max_digits=20),
        ),
        migrations.AddField(
            model_name='dateaggregatedmetrics',
            name='weighted_period_return_percent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Weighted average this-period percentage return (weighted by AUM)', max_digits=10),
        ),
    ]
