# Generated by Django 4.2.23 on 2025-10-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_add_period_returns_to_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateaggregatedmetrics',
            name='total_monthly_return_dollar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aggregated monthly dollar returns (month-end to month-end)', max_digits=20),
        ),
        migrations.AddField(
            model_name='dateaggregatedmetrics',
            name='weighted_monthly_return_percent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Weighted average monthly percentage return (weighted by AUM)', max_digits=10),
        ),
    ]
